name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.11
      - name: setup dependencies
        run: |
          pip install uv twine
          uv sync
      #   - name: run test
      #     run: uv run pytest -x
      - name: publish
        run: |
          uv build
          twine upload --skip-existing dist/* -u $PYPI_USER -p $PYPI_PWD
        env:
          PYPI_USER: __token__
          PYPI_PWD: ${{ secrets.PYPI_TOKEN }}
